/**
 * Single source of truth for SEO constants and shared JSON-LD schemas.
 *
 * NOTE: SITE_URL points at the live Vercel deployment for now. When the custom
 * domain goes live, change it to "https://aastack.dev" and everything that
 * derives from it (canonicals, og:url, sitemap, schema) updates automatically.
 */
import type { Metadata } from "next";

export const SITE_URL = "https://aastack-solutions.vercel.app";

export const SITE_NAME = "AAStack Solutions";

export const CONTACT_EMAIL = "team.aastack@gmail.com";
export const CONTACT_PHONE = "+923250854670";

/** Shared 1200×630 social share image (generated by app/og/route.tsx). */
export const OG_IMAGE = {
  url: `${SITE_URL}/og`,
  width: 1200,
  height: 630,
  alt: "AAStack Solutions — Build Smarter. Launch Faster. Rank Higher.",
};

/**
 * Builds a complete, self-contained Metadata object for a page.
 *
 * Next overwrites the `openGraph`/`twitter` objects per route segment (they are
 * not deep-merged with the root layout), so each page must declare them in full.
 * The OG/Twitter image is supplied site-wide by app/opengraph-image.tsx.
 *
 * `title` is set as `absolute` so the carefully sized per-page titles render
 * exactly as written, without the layout's "%s | AAStack Solutions" template
 * appending a second brand suffix.
 */
export function pageMetadata(opts: {
  title: string;
  description: string;
  keywords: string[];
  /** Path beginning with "/", e.g. "/about" (use "/" for home). */
  path: string;
}): Metadata {
  const { title, description, keywords, path } = opts;
  const url = path === "/" ? `${SITE_URL}/` : `${SITE_URL}${path}`;

  return {
    title: { absolute: title },
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      locale: "en_PK",
      siteName: SITE_NAME,
      url,
      title,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

/**
 * Organization schema reused on the Home and About pages. Built from the
 * central constants so contact details never drift.
 */
export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/logo-mark.webp`,
  description:
    "AAStack Solutions builds custom web apps, mobile apps, AI chatbots, and automation systems for businesses worldwide.",
  email: CONTACT_EMAIL,
  telephone: CONTACT_PHONE,
  address: {
    "@type": "PostalAddress",
    streetAddress: "Shahrah-e-Faisal",
    addressLocality: "Karachi",
    addressRegion: "Sindh",
    addressCountry: "PK",
  },
  sameAs: [
    "https://www.linkedin.com/company/aastack-solutions/",
    "https://aastack.dev",
  ],
  foundingDate: "2024",
  knowsAbout: [
    "Web Development",
    "Mobile App Development",
    "AI Automation",
    "n8n Workflow Automation",
    "Chatbot Development",
    "RAG Pipelines",
    "SEO Optimization",
    "Flutter Development",
    "Next.js",
    "React",
  ],
} as const;
